# Generated by Django 5.0.1 on 2024-01-23 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeojsonObjects",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        default="uploads/default.geojson", upload_to="uploads/"
                    ),
                ),
                ("geojson_obj", models.JSONField()),
                ("tag", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "verbose_name": "GeojsonObject",
            },
        ),
        migrations.CreateModel(
            name="Records",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("record_id", models.CharField(default=uuid.uuid4, max_length=36)),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("image", models.CharField(max_length=48)),
            ],
            options={
                "verbose_name": "Record",
            },
        ),
    ]
